version: '3.8'

services:
  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    ports:
      - "9104:9104"
    env_file:
      - backend.env
    entrypoint: >
      sh -c "mysqld_exporter --mysqld.username=root:$MYSQL_ROOT_PASSWORD \
             --mysqld.address=$MYSQL_HOST:$MYSQL_PORT"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitoring/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - app_network

  controller:
    image: ngrinder/controller:latest
    container_name: controller
    ports:
      - "8181:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ngrinder_controller_data:/opt/ngrinder-controller
    networks:
      - app_network

  ngrinder-agent:
    image: ngrinder/agent:latest
    container_name: ngrinder-agent
    networks:
      - app_network
    links:
      - controller
    restart: always

volumes:
  prometheus-data:
  grafana-data:
  ngrinder_controller_data:

networks:
  app_network:
    external: true
    name: hiteen_app_network
