version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3307:3306"
    env_file: "backend.env"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
